### ISSUE TITLE
Add marketplace annotations

### ISSUE THREAD

**Issue by luebken** [coopnorge/provider-github#19]
Hey @AtzeDeVries. Thanks for this great provider! For a nice rendering of the provider in the Marketplace, we like to ask to put the Crossplane standard annotations into the `crossplane.yaml`: https://docs.crossplane.io/v1.10/reference/xpkg/#object-annotations. This would also make sure the marketplace listing links back to this GitHub repo. If you need help, don't hesitate to reach out.

**Comment by AtzeDeVries** [comment]
@luebken thanks for the info. I add the metadata.
