### ISSUE TITLE
Usage with GitHub-enterprise GitHub instance

### ISSUE THREAD

**Issue by sebastienbrunkyndryl** [coopnorge/provider-github#23]
Hello,

In order to use the provider with a GitHub-enterprise instance it's required to set base_url property, but I don't retrieve the properties into to "providerconfigs.github.upbound.io" CRD.

Could you add an example to explain how to make it ?

**Comment by gilfthde** [comment]
I can confirm that adding the `base_url` property into the `credentials` JSON object works.

**Comment by AtzeDeVries** [comment]
@sebastienbrunkyndryl  i am going to close it, but feel free to reopen if this issue is not resolved.
