### ISSUE TITLE
Still active?

### ISSUE THREAD

**Issue by RobCannon** [coopnorge/provider-github#32]
Is this project still active?  The latest code commit is from May and I created an issue and there has been no response.  I would like to commit some code to support webhooks, but I am concerned no one is paying attention.

**Comment by AtzeDeVries** [comment]
it is still active, but very busy. Thanks for checking in.

**Comment by vladfr** [comment]
I'm planning to use this some time soon, to manage team memberships. I'd like to add some more resources for that. @AtzeDeVries are there any plans to update it to the latest versions? Go 1.21 and latest upjet would be nice!

**Comment by RobCannon** [comment]
Just wanted to add that I still want to contribute, but we have been slammed at my company with end-of-year work, so hopefully I can get back to this in January.

**Comment by AtzeDeVries** [comment]
Hi,

I had some struggles to make time for this provider, but it has become relevant again so i have time to work on it again. PRs are very welcome!
