### ISSUE TITLE
Logs not displayed

### ISSUE THREAD

**Issue by tomasmota** [coopnorge/provider-github#49]
Hi I set up the provider, and after trying to create a resource this is what the pod logs looked like:

![image](https://github.com/coopnorge/provider-github/assets/25929015/5cde66dc-9277-4822-92bc-d500ad3b7e82)

Please let me know if I need to do something different or if it's a bug.

**Comment by AtzeDeVries** [comment]
Mmm i have never seen this before. What version on XP are you running? It might be smart also to check at the Crossplane Slack community.

**Comment by tomasmota** [comment]
oh could be that, thanks
