### ISSUE TITLE
Not able to send GitHub usr invitation

### ISSUE THREAD

**Issue by A660988** [coopnorge/provider-github#76]
I am using upbound coopnorge/provider-github@v0.10.0 provider and fine-grined token. 

created provider-config and secret.
Below is my claim for user invitation:
apiVersion: user.github.upbound.io/v1alpha1
kind: Membership
metadata:
  annotations:
    meta.upbound.io/example-id: user/v1alpha1/membership
  labels:
    testing.upbound.io/example-name: membership_for_some_user
  name: membership-for-some-user
spec:
  forProvider:
    role: member
    username: user-github-id
  providerConfigRef:
    name: default
    
   After claiming it says external resource created. But invitation does not go to user

**Comment by AtzeDeVries** [comment]
can you post some related logs of the provider and the status field of the resource?

**Comment by A660988** [comment]
Thanks for reply

I have fetched the object and it is giving me error 
 - lastTransitionTime: "2024-06-24T06:30:04Z"
    **message: 'apply failed: this resource can only be used in the context of an organization,
      "GLB-ATOS-MSCC" is a user:**
  
  Following is my object
  
  apiVersion: user.github.upbound.io/v1alpha1
kind: Membership
metadata:
  annotations:
    crossplane.io/external-create-pending: "2024-06-24T12:25:23Z"
    crossplane.io/external-create-succeeded: "2024-06-24T12:25:23Z"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"user.github.upbound.io/v1alpha1","kind":"Membership","metadata":{"annotations":{"meta.upbound.io/example-id":"user/v1alpha1/membership"},"labels":{"testing.upbound.io/example-name":"membership_for_some_user"},"name":"membership-for-some-user"},"spec":{"forProvider":{"role":"member","username":"sn-atos"}}}
    meta.upbound.io/example-id: user/v1alpha1/membership
  creationTimestamp: "2024-06-24T06:24:35Z"
  finalizers:
  - finalizer.managedresource.crossplane.io
  generation: 9
  labels:
    testing.upbound.io/example-name: membership_for_some_user
  name: membership-for-some-user
  resourceVersion: "141813241"
  uid: c11b43b2-8577-4a6d-b758-03f8c26545e2
spec:
  deletionPolicy: Delete
  forProvider:
    role: member
    username: sn-atos
  initProvider: {}
  managementPolicies:
  - '*'
  providerConfigRef:
    name: default
status:
  atProvider: {}
  conditions:
  - lastTransitionTime: "2024-06-24T06:24:35Z"
    reason: Creating
    status: "False"
    type: Ready
  - lastTransitionTime: "2024-06-24T08:45:06Z"
    reason: ReconcileSuccess
    status: "True"
    type: Synced
  - lastTransitionTime: "2024-06-24T06:30:04Z"
    message: 'apply failed: this resource can only be used in the context of an organization,
      "GLB-ATOS-MSCC" is a user: '
    reason: ApplyFailure
    status: "False"
    type: LastAsyncOperation
  - lastTransitionTime: "2024-06-24T12:25:24Z"
    reason: Finished
    status: "True"
    type: AsyncOperation
    
    
I have used fine Fine-grained access token. 
I check document and it says to use GitHub App user access tokens.

So I am going to try with GitHub App user access tokens.

**Comment by A660988** [comment]
log 
![image](https://github.com/coopnorge/provider-github/assets/75358240/e003faf4-1817-4cf6-9e1a-1bbf1e7a90f1)

**Comment by AtzeDeVries** [comment]
are you in a github organization? If so, are you sure you are pointing (in the providerconfig) to the right one? This resource only works in organizations.

Ref: https://registry.terraform.io/providers/integrations/github/latest/docs/resources/membership

**Comment by A660988** [comment]
Thanks for your help. I was not able to invite users due to 2 things:
1. Did not use the GitHub app user access token
2. Did not use valid github provider config.

I modified github providerConfig and used GitHub app access token instead of PAT and it worked.
