### ISSUE TITLE
ActionsSecret from a Secret

### ISSUE THREAD

**Issue by vfarcic** [coopnorge/provider-github#78]
Feature request:

Add the option to use (reference) a Kubernetes Secret as a value in ActionSecret.

**Comment by AtzeDeVries** [comment]
Hi @vfarcic 

I think this feature is already there https://github.com/coopnorge/provider-github/blob/main/package/crds/actions.github.upbound.io_actionssecrets.yaml#L76-L113. 

Does this cover your feature request?

**Comment by vfarcic** [comment]
My bad. I somehow missed it. Sorry for that.
